controller_manager:
  ros__parameters:
    update_rate: 100  # 控制器管理器更新频率为100Hz，即每秒更新100次
    use_sim_time: true  # 使用模拟时间（在仿真环境中通常启用）
    
    # 关节状态广播器，用于广播机器人的关节状态（如位置、速度等）
    fishbot_joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster  # 使用 JointStateBroadcaster 类型
      use_sim_time: true  # 使用模拟时间
    
    # 力矩控制器，用于控制机器人左右轮子的力矩（力）
    fishbot_effort_controller:
      type: effort_controllers/JointGroupEffortController  # 使用 JointGroupEffortController 类型
    
    # 差速驱动控制器，控制左右轮子以实现机器人运动
    fishbot_diff_drive_controller:
      type: diff_drive_controller/DiffDriveController  # 使用 DiffDriveController 类型

# fishbot_effort_controller 力控制器配置
fishbot_effort_controller:
  ros__parameters:
    joints:
      - left_wheel_joint  # 左轮关节名称
      - right_wheel_joint  # 右轮关节名称
    command_interfaces:
      - effort  # 使用 'effort' 接口控制力矩（例如驱动轮子的扭矩）
    state_interfaces:
      - position  # 关节的 'position' 接口（例如轮子的角度）
      - velocity  # 关节的 'velocity' 接口（例如轮子的速度）
      - effort  # 关节的 'effort' 接口（例如轮子的力矩）

# fishbot_diff_drive_controller 差速控制器配置
fishbot_diff_drive_controller:
  ros__parameters:
    left_wheel_names: ["left_wheel_joint"]  # 左轮的关节名称
    right_wheel_names: ["right_wheel_joint"]  # 右轮的关节名称

    wheel_separation: 0.17  # 左右轮之间的距离（单位：米）
    wheel_radius: 0.032  # 轮子的半径（单位：米）

    # 用于调整轮子半径和轮距的倍数，通常不修改
    wheel_separation_multiplier: 1.0  
    left_wheel_radius_multiplier: 1.0  
    right_wheel_radius_multiplier: 1.0

    # 发布频率
    publish_rate: 50.0  # 每秒发布 50 次控制信息
    
    # 里程计坐标系和机器人基座坐标系的名称
    odom_frame_id: odom  # 里程计的坐标系
    base_frame_id: base_footprint  # 机器人基座的坐标系
    
    # 机器人位置（pose）和速度（twist）的协方差，表示不确定性
    pose_covariance_diagonal: [0.001, 0.001, 0.0, 0.0, 0.0, 0.01]  # 位姿的协方差
    twist_covariance_diagonal: [0.001, 0.0, 0.0, 0.0, 0.0, 0.01]  # 速度的协方差

    # 开环控制，表示不使用反馈来调整控制
    open_loop: true  # 启用开环控制（不依赖于传感器反馈）

    # 启用里程计TF广播，使其他节点可以接收机器人的位置和姿态
    enable_odom_tf: true  # 启用里程计的TF转换广播

    # 控制命令超时，控制器在此时间内如果没有接收到新的速度命令，则停止移动
    cmd_vel_timeout: 0.5  # 控制命令超时，单位：秒
    
    # 以下选项为高级设置，通常在特定场景下使用
    # publish_limited_velocity: true  # 发布限制的速度（可选）
    use_stamped_vel: false  # 是否使用时间戳的速度命令（默认为false）
    # velocity_rolling_window_size: 10  # 速度的滚动窗口大小（可选）
