<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
    <xacro:include filename="$(find fishbot)/urdf/common_inertia.xacro" />  <!-- 引入惯性矩阵的文件 -->
    <xacro:macro name="base_xacro" params="length radius">   <!-- 定义一个宏，名字是base_link，包含两个参数 -->
        <!-- 声明一个虚拟的部件 -->
        <link name="base_footprint" />
        <!-- 声明 base_link模块 -->
        <link name="base_link">
            <visual>
                <origin xyz="0 0 0" rpy="0 0 0" />
                <geometry>
                    <cylinder length="${length}" radius="${radius}" />
                </geometry>
                <material name="blue">
                    <color rgba="0.1 0.1 1.0 0.5" />
                </material>
            </visual>
            <collision>   <!-- 碰撞属性，这里和visual保持一致就行 -->
                <origin xyz="0 0 0.0" rpy="0 0 0" />
                <geometry>
                    <cylinder length="${length}" radius="${radius}" />
                </geometry>
                <material name="blue">
                    <color rgba="0.1 0.1 1.0 0.5"/>
                </material>
            </collision>
            <xacro:cylinder_inertia m="1.0" r="${radius}" h="${length}"/>  <!-- 加入惯性矩阵 -->
        </link>
        <!-- 把虚拟部件链接到底盘上面，不要让车子陷入地底下了 -->
        <joint name="base_joint" type="fixed">
            <parent link="base_footprint" />
            <child link="base_link" />
            <origin xyz="0.0 0.0 ${length/2.0+0.032-0.001}" rpy="0 0 0" />
        </joint>
    </xacro:macro>
</robot>
